### PR TITLE
Racs labbces brazil

### PR DESCRIPTION
**Pull request by SantosRAC**
Added a script that builds the TSV file with GO annotation from InterProScan output TSV file.
Made small fixes in documentation ('building pages' and method docstrings).

### CODE REVIEW

**Comment by sepro** [comment]
Thanks for the improvements to the docs/docstring!

How to handle the additional script I'll have to think about. Ideally InterProScan's output, with GO information, should be supported as a way to import GO from the admin panel. On the other hand it does solve an issue right now, and it is unlikely I'll have time to properly implement it any time soon.

**Comment by sepro** [comment]
@SantosRAC I've reviewed the script and it has a few issues (which can be discussed). So currently I can't pull this in.

**Comment by SantosRAC** [comment]
> @SantosRAC I've reviewed the script and it has a few issues (which can be discussed). So currently I can't pull this in.

Of course, @sepro ! It would be a great pleasure for me to discuss about this script and other things our group plan for CoNekT (if you have time). Please, let me know if you can meet close to Oct 15 - I can adapt to your time!

**Comment by sepro** [comment]
@SantosRAC I'll send you an email when I'm back from my holidays to see if we can set something up around that date 👍

**Comment by SantosRAC** [comment]
No problem! Thanks a lot, @sepro !

**Pull request merged**
